package com.tw;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testStudentGetInputFromString() throws Exception {

        Student student = new Student();

        String string = "王一, 1230012, 英语: 56.2, 数学: 60, 语文: 80, 编程: 99";
        assertTrue(student.getInputFromString(string));

        string = "王一, 1230012, 英语: 56.2, 数学: 60, 编程: 99";
        assertFalse(student.getInputFromString(string));
    }

    @Test
    public void testReportCardGetOutputArgumentsFromString() throws Exception {

        ReportCard report_card = new ReportCard();

        String string = "123, 233, 12312312";
        assertTrue(report_card.getOutputArgumentsFromString(string));

        string = "123, 1230012, , 123211";
        assertFalse(report_card.getOutputArgumentsFromString(string));
    }

}
